name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *" # Her 24 saatte bir otomatik çalışır
  workflow_dispatch: # Manuel çalıştırma izni verir
  push:
    branches:
      - main # Ana branch adın master ise burayı master yap

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate-snake-game
        uses: Platane/snk@v3
        with:
          github_user_name: brky06
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
